import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';
import { CreditCard, ArrowLeft, Check, Shield, Crown, Users, Headphones, UserCheck } from 'lucide-react';

declare global {
  interface Window {
    Razorpay: any;
  }
}

interface VIPPlan {
  id: string;
  name: string;
  price: number;
  originalPrice: number;
  features: string[];
  icon: React.ReactNode;
}

const vipPlan: VIPPlan = {
  id: 'vip-tenant',
  name: 'VIP Tenant',
  price: 499,
  originalPrice: 9999,
  features: [
    '25 Contacts',
    'Priority Support',
    'Dedicated Relationship Manager Assigned'
  ],
  icon: <Crown className="w-6 h-6" />
};

const PaymentPage = () => {
  const navigate = useNavigate();
  const { user, isAuthenticated, login, loginError, clearLoginError } = useAppContext();
  const [processing, setProcessing] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
    document.title = 'Upgrade to VIP Tenant | Homemates';
    
    // Load Razorpay script
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    document.body.appendChild(script);
    
    return () => {
      document.body.removeChild(script);
    };
  }, []);

  const handlePayment = async () => {
    if (!user) return;

    setProcessing(true);
    try {
      // Create order on your backend (you'll need to implement this endpoint)
      // For now, using a mock order creation
      const orderResponse = await fetch('/api/create-razorpay-order', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          amount: vipPlan.price * 100, // Amount in paise
          currency: 'INR',
          receipt: `vip_${user.id}_${Date.now()}`,
        }),
      });

      // If backend endpoint doesn't exist, use Razorpay Checkout directly
      if (!orderResponse.ok) {
        // Direct Razorpay Checkout integration
        const options = {
          key: process.env.VITE_RAZORPAY_KEY_ID || 'rzp_test_1DP5mmOlF5G5ag', // Replace with your Razorpay key
          amount: vipPlan.price * 100, // Amount in paise
          currency: 'INR',
          name: 'Homemates',
          description: 'VIP Tenant Plan',
          image: '/images/homemates-logo.png',
          order_id: null, // Will be generated by Razorpay
          handler: function (response: any) {
            // Handle successful payment
            console.log('Payment successful:', response);
            alert('Payment successful! Your VIP Tenant plan is now active.');
            // Update user's premium status in Firestore
            updateUserVIPStatus(user.id);
            navigate('/profile');
          },
          prefill: {
            name: user.displayName || user.name || '',
            email: user.email || '',
            contact: user.phoneNumber || '',
          },
          theme: {
            color: '#C2185B',
          },
          modal: {
            ondismiss: function() {
              setProcessing(false);
            },
          },
        };

        const razorpay = new window.Razorpay(options);
        razorpay.open();
        return;
      }

      const orderData = await orderResponse.json();
      
      const options = {
        key: process.env.VITE_RAZORPAY_KEY_ID || 'rzp_test_1DP5mmOlF5G5ag',
        amount: vipPlan.price * 100,
        currency: 'INR',
        name: 'Homemates',
        description: 'VIP Tenant Plan',
        image: '/images/homemates-logo.png',
        order_id: orderData.id,
        handler: function (response: any) {
          // Verify payment on backend and update user status
          verifyPayment(response, user.id);
        },
        prefill: {
          name: user.displayName || user.name || '',
          email: user.email || '',
          contact: user.phoneNumber || '',
        },
        theme: {
          color: '#C2185B',
        },
        modal: {
          ondismiss: function() {
            setProcessing(false);
          },
        },
      };

      const razorpay = new window.Razorpay(options);
      razorpay.open();
    } catch (error) {
      console.error('Payment error:', error);
      alert('Payment failed. Please try again.');
      setProcessing(false);
    }
  };

  const verifyPayment = async (response: any, userId: string) => {
    try {
      const verifyResponse = await fetch('/api/verify-razorpay-payment', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          razorpay_order_id: response.razorpay_order_id,
          razorpay_payment_id: response.razorpay_payment_id,
          razorpay_signature: response.razorpay_signature,
        }),
      });

      if (verifyResponse.ok) {
        await updateUserVIPStatus(userId);
        alert('Payment successful! Your VIP Tenant plan is now active.');
        navigate('/profile');
      } else {
        alert('Payment verification failed. Please contact support.');
      }
    } catch (error) {
      console.error('Verification error:', error);
      alert('Payment verification failed. Please contact support.');
    } finally {
      setProcessing(false);
    }
  };

  const updateUserVIPStatus = async (userId: string) => {
    try {
      const { doc, updateDoc } = await import('firebase/firestore');
      const { db } = await import('../config/firebase');
      await updateDoc(doc(db, 'u', userId), {
        isPremium: true,
        isVIP: true,
        vipPlan: 'vip-tenant',
        vipActivatedAt: new Date().toISOString(),
        contactsRemaining: 25,
      });
    } catch (error) {
      console.error('Error updating VIP status:', error);
    }
  };

  const handleLogin = async () => {
    clearLoginError(); // Clear any previous errors
    await login();
  };

  if (!isAuthenticated) {
    return (
      <div className="py-20">
        <div className="container">
          <div className="max-w-md mx-auto text-center">
            <CreditCard className="w-16 h-16 mx-auto text-gray-400 mb-4" />
            <h2 className="text-2xl font-bold mb-2">Sign In Required</h2>
            <p className="text-gray-600 mb-6">
              Please sign in to upgrade to VIP Tenant
            </p>
            <div className="relative">
              <button 
                onClick={handleLogin}
                className="flex items-center justify-center w-full btn btn-primary"
              >
                Sign in with Google
              </button>
              {loginError && (
                <div className="mt-2">
                  <p className="text-red-600 text-sm font-bold bg-red-100 border border-red-200 rounded px-2 py-1 w-full" aria-live="polite">
                    {loginError}
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="py-8">
      <div className="container max-w-4xl">
        {/* Header */}
        <div className="mb-8">
          <button 
            onClick={() => navigate(-1)}
            className="flex items-center text-gray-600 hover:text-gray-900 mb-4"
          >
            <ArrowLeft className="w-4 h-4 mr-1" />
            Back
          </button>
          
          <div className="text-center">
            <h1 className="text-3xl font-bold mb-2">Upgrade to VIP Tenant</h1>
            <p className="text-gray-600 mb-4">
              Get exclusive benefits and premium features
            </p>
          </div>
        </div>

        {/* VIP Plan Card */}
        <div className="max-w-2xl mx-auto">
          <div className="relative border-2 border-primary-600 rounded-lg p-8 bg-gradient-to-br from-primary-50 to-white shadow-lg">
            <div className="text-center mb-6">
              <div className="flex justify-center mb-4">
                <div className="p-4 rounded-full bg-primary-100 text-primary-600">
                  {vipPlan.icon}
                </div>
              </div>
              
              <h3 className="text-2xl font-bold mb-2">{vipPlan.name}</h3>
              
              <div className="flex items-center justify-center gap-4 mb-6">
                <span className="line-through text-gray-400 text-xl">₹{vipPlan.originalPrice.toLocaleString()}</span>
                <span className="text-4xl font-bold text-primary-600">₹{vipPlan.price}</span>
              </div>
            </div>

            {/* Features */}
            <div className="space-y-4 mb-8">
              <h4 className="text-lg font-semibold mb-4 text-center">What's Included:</h4>
              {vipPlan.features.map((feature, index) => (
                <div key={index} className="flex items-start gap-3 p-3 bg-white rounded-lg">
                  <Check className="w-5 h-5 text-pink-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">{feature}</span>
                </div>
              ))}
            </div>

            {/* Payment Button */}
            <div className="text-center">
              <button
                onClick={handlePayment}
                disabled={processing}
                className="w-full btn btn-primary btn-lg flex items-center justify-center"
              >
                {processing ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                    Processing Payment...
                  </>
                ) : (
                  <>
                    <CreditCard className="w-5 h-5 mr-2" />
                    Upgrade Now - ₹{vipPlan.price}
                  </>
                )}
              </button>
              
              <div className="flex items-center justify-center mt-4 text-sm text-gray-500">
                <Shield className="w-4 h-4 mr-1" />
                Secure payment powered by Razorpay
              </div>
            </div>
          </div>
        </div>

        {/* Benefits Section */}
        <div className="mt-12 bg-gray-50 rounded-lg p-6">
          <h3 className="text-xl font-bold mb-4 text-center">VIP Tenant Benefits</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Users className="w-6 h-6 text-primary-600" />
              </div>
              <h4 className="font-semibold mb-2">25 Contacts</h4>
              <p className="text-gray-600 text-sm">Contact up to 25 property owners directly</p>
            </div>
            
            <div className="text-center">
              <div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Headphones className="w-6 h-6 text-primary-600" />
              </div>
              <h4 className="font-semibold mb-2">Priority Support</h4>
              <p className="text-gray-600 text-sm">Get faster response times and dedicated help</p>
            </div>
            
            <div className="text-center">
              <div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <UserCheck className="w-6 h-6 text-primary-600" />
              </div>
              <h4 className="font-semibold mb-2">Dedicated Manager</h4>
              <p className="text-gray-600 text-sm">Your personal relationship manager for assistance</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PaymentPage; 