import React from 'react';

const TermsAndConditionsPage = () => (
  <div className="container py-8 max-w-3xl mx-auto">
    <h1 className="text-2xl font-bold mb-4">Terms &amp; Conditions</h1>
    <div className="prose prose-sm sm:prose lg:prose-lg max-w-none">
      <p>This document is an electronic record in terms of the Information Technology Act, 2000 and the applicable rules thereunder, as well as the amended provisions related to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
      <p>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which mandate the publication of rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <strong><a href="http://www.homematesapp.in" target="_blank" rel="noopener noreferrer">www.homematesapp.in</a></strong> (“Website”), including the related mobile site and mobile application (collectively referred to as the “Platform”).</p>
      <p>The Platform is owned and operated by <strong>Nhancio Technologies Pvt. Ltd.</strong>, a company incorporated under the Companies Act, 1956, with its registered office at <strong>Hyderabad, Telangana, India</strong> (hereinafter referred to as "Homemates AI", "Platform Owner", "we", "us", or "our").</p>
      <p>Your use of the Platform and Services is governed by the following terms and conditions ("Terms of Use"), including applicable policies, all of which are incorporated herein by reference. By merely using the Platform, you are contracting with the Platform Owner, and these Terms of Use, including the policies, constitute your binding obligations.</p>
      <p>These Terms of Use relate to your use of our Platform, digital subscriptions, tools, and AI-powered services (collectively, “Services”). Any additional or conflicting terms proposed by you are expressly rejected and shall have no force or effect.</p>
      <p>These Terms of Use may be modified at any time without assigning any reason. It is your responsibility to periodically review them to stay updated.</p>

      <hr className="my-6" />

      <h2 className="text-xl font-semibold mt-6 mb-2">1. User Eligibility &amp; Account Responsibilities</h2>
      <p>For the purpose of these Terms, “you”, “your”, or “user” means any natural or legal person who has registered or accessed the Platform and/or subscribed to our Services.</p>
      <p>To access and use the Services, you agree to provide true, accurate, and complete information and to maintain the security and confidentiality of your account credentials. You are solely responsible for all activities that occur under your account.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. Nature of Service</h2>
      <p>Homemates AI is a digital subscription service that uses artificial intelligence to match individuals with compatible roommates and co-living preferences. You understand and agree that our Services are based on algorithmic matching, and final decisions are user-driven. We make no guarantees regarding outcomes, compatibility, or success in finding a roommate.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Intellectual Property</h2>
      <p>All contents, features, and functionality on the Platform, including but not limited to text, graphics, logos, AI models, and software, are proprietary to Homemates AI. You are not granted any rights to use our intellectual property without prior written consent.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. Usage Restrictions</h2>
      <ul className="list-disc ml-6 mb-2 text-gray-700">
        <li>Use the Platform for any unlawful, fraudulent, or harmful purpose.</li>
        <li>Reverse-engineer, copy, resell, or commercially exploit the Services.</li>
        <li>Misrepresent yourself or submit false information.</li>
      </ul>
      <p>Unauthorized use of the Platform or breach of these terms may lead to legal action under applicable laws.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">5. Third-Party Links</h2>
      <p>Our Platform may contain links to third-party websites or services. Such links are provided for convenience and informational purposes only. Accessing third-party platforms is at your own risk and subject to their respective terms and policies.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">6. Subscription and Payments</h2>
      <p>By subscribing to our Services, you agree to pay all applicable fees as displayed on the Platform. Subscriptions are billed on a recurring basis unless cancelled by you prior to the renewal date. All payments are non-refundable unless otherwise stated.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">7. Disclaimer of Warranties</h2>
      <p>We do not warrant the accuracy, completeness, or reliability of the Platform or Services. The Services are provided “as is” and “as available” without warranties of any kind, either express or implied. Use of the Platform is at your own risk.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">8. Limitation of Liability</h2>
      <p>In no event shall Homemates AI or its affiliates be liable for indirect, incidental, special, consequential or punitive damages, including loss of profits or data. Our total liability shall not exceed the subscription fee paid by you for the Service or Rs. 100, whichever is lower.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">9. Indemnity</h2>
      <p>You agree to indemnify and hold harmless Homemates AI, its affiliates, officers, employees, and agents from any claim, liability, loss, or expense, including reasonable attorneys' fees, arising from your use of the Platform or breach of these Terms.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">10. Force Majeure</h2>
      <p>We shall not be liable for any delay or failure in performance due to events beyond our reasonable control, including but not limited to acts of God, natural disasters, internet failures, or legal restrictions.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">11. Governing Law &amp; Jurisdiction</h2>
      <p>These Terms shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts at <strong>Hyderabad, Telangana, India</strong>.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">12. Contact Information</h2>
      <p>For any questions, concerns, or disputes, you may reach out to us through the contact form or support email provided on our website: <a href="http://www.homematesapp.in" target="_blank" rel="noopener noreferrer">www.homematesapp.in</a></p>
    </div>
  </div>
);

export default TermsAndConditionsPage;
